### ISSUE TITLE
Implement real-time voice transcripts 

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#30]
When someone gives a specific voice command, have the text pop up on screen. For example, start with Hey Scout!

**Comment by Henrynaut** [comment]
- [ ] Get speech to text working with Azure LUIS AI
- [ ] Create a general voice command "Science Log" to start recording a log
- [ ] Display text from Azure LUIS as a 3D text mesh pro
- [ ] Display text on a lunarpedia page

**Comment by BrockBalthazor** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/what-is-luis
https://www.luis.ai/

**Comment by Henrynaut** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/index-speech-to-text
