### ISSUE TITLE
Create an animated hologram/AR Overlay

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#31]
This AR overlay would be instructional, such as an animated floating arrow showing where to plug a cable into a socket

- [x] Add hologram arrow
- [x] Create animations for arrow
- [x] Make arrow moveable
- [x] Switch moving hologram
- [x] Box hologram

**Comment by Henrynaut** [comment]
This AR overlay would be instructional, such as an animated floating arrow showing where to plug a cable into a socket

**Comment by Laurenbrady01** [comment]
Switch moving hologram
moveable hologram
box hologram

**Comment by Henrynaut** [comment]
Lauren Created laser
![image](https://user-images.githubusercontent.com/8094027/107597580-b21ca480-6be0-11eb-9e8e-866fce9af040.png)

**Comment by Henrynaut** [comment]
We can manually place these in certain locations for a demo for The SDR
