### ISSUE TITLE
Create a display of ETA to a waypoint

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#32]
Find out how to have an Estimated Time of Arrival show up in a floating panel, that counts down based on user position

**Comment by Henrynaut** [comment]
- [x]  Create TextMeshPro object in a MRTK panel
- [x]  Get text to change value based on a float variable in C#
- [ ]  Calculate distance of character away from waypoint (maybe the rover)
- [ ]  Calculate ETA based on distance, then update the text object

**Comment by Henrynaut** [comment]
Brock needs help figuring out what the waypoint object is called. 

`new Vector3 WaypointOne = markerClone.transform.position`

![image](https://user-images.githubusercontent.com/8094027/109096507-4445a200-76e3-11eb-9626-e7193da88f85.png)

**Comment by Henrynaut** [comment]
@Henrynaut Help set up the transform variable for Brock

**Comment by Henrynaut** [comment]
On development Friday we can work on this together in person to get everything finished

**Comment by BrockBalthazor** [comment]
Distance Calculation works
Bearing Calculation Broken

- [ ] Waypoint selector
- [x] ETA vs 
- [x] Distance
- [ ] Figure out spatial anchor thing with coordinate system

**Comment by Henrynaut** [comment]
It would also be a good feature if we could change the waypoint spline color based on ETA, such as in this example (Red splines for routes that are hard/take a long time, Green splines for routes that will be quick). This could be done with the existing catmull rom waypoint spline system we have
![image](https://user-images.githubusercontent.com/8094027/112052104-b8c40300-8b20-11eb-9b97-c12356806be4.png)

**Comment by BrockBalthazor** [comment]
- [x] Note out time
- [x] Reduce decimals on distance
- [x] Possibly reduce update on distance 
- [x] Camera distance as one waypoint so it updates as user moves
