### ISSUE TITLE
Start brainstorming wrist control design 1.0

### ISSUE THREAD

**Issue by IzzyGomezThree** [The12thAstronaut/SUITS-2021#35]
We gotta make this awesome sci-fi looking wrist control that has such a cool design, that the Star Wars movie peeps hire us for their next movie.

(and it's gotta be functional too)

**Comment by mannycarr214** [comment]
Sorry to jump in but one idea I have is something similar to Boba Fetts wrist controller! We can make the buttons big similar to a jitter bug phone where it basically has a line of buttons each doing a separate task and then adding a drawing pad on the bottom that flips over

**Comment by IzzyGomezThree** [comment]
No need to be sorry :)
Mmm, that's a great idea, the flipping over part might be a challenge design wise, but the big buttons is a great idea!! I'll take a look at Bob's wrist thing asap
