### ISSUE TITLE
Enable ability to display and track multiple waypoints on the horizontal compass

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#46]
- [ ] Integrate with MRTK
- [ ] Display waypoint for Lander & Rover at  the same time
- [ ] Instead of just having a name for the waypoint, show a mini-hologram/icon of the destination, above the marker
- [x] Create Distance Tracker
- [ ] Change color of marker based on waypoint distance away from user

**Comment by mannycarr214** [comment]
I'm not sure where to start in regards to displaying two pointers at the same time! Anything helps

**Comment by Henrynaut** [comment]
For multiple pointers/markers, we can edit the compass by making the torus/donut the parent game object.  Right now the pointer/marker is using the LookAt function to look at the rover, but we'd like to create another marker that simultaneously points at another waypoint, such as a lander.

We should each marker a child of the ring/donut shape.

**Comment by Henrynaut** [comment]
The way we have it set up with the look at function it forces the whole game object to look at the target. To fix that we need to figure out how to attach the look at function to just the pointers. To combat that Manny was looking at ellipse code to help with the rotations.
