### ISSUE TITLE
Attach floating hologram overlay to help with UIA or DCU interaction

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#52]
![image](https://user-images.githubusercontent.com/8094027/109095216-ef089100-76e0-11eb-9221-1695e0d2f5c8.png)

**Comment by Laurenbrady01** [comment]
The hologram switch bounding box needs to be resized but here is the progress thus far
Also, these switches are not tied to a specific procedure yet

![image](https://user-images.githubusercontent.com/55027585/110283183-42ae9080-7fa5-11eb-9c97-5cd6af4be992.png)
