### ISSUE TITLE
Import 3D models for the scenarios (UIA, DCU, Lunar Lander)

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#53]
![image](https://user-images.githubusercontent.com/8094027/109097748-9091e180-76e5-11eb-8319-29cb4d9b0b2e.png)

**Comment by Laurenbrady01** [comment]
![image](https://user-images.githubusercontent.com/55027585/110283163-3b878280-7fa5-11eb-8222-8ba4c8559d25.png)
