### ISSUE TITLE
Make hologram shader for 3D models in our project

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#57]
Follow this tutorial to make a hologram-like shader for SCOUT in Unity https://youtu.be/wtZ5WcrV-9A

![image](https://user-images.githubusercontent.com/8094027/109873701-bd894b80-7c33-11eb-9c8d-254bedb2c766.png)

**Comment by Laurenbrady01** [comment]
![image](https://user-images.githubusercontent.com/55027585/110255503-bf1b8200-7f59-11eb-857f-b69bffa62cf1.png)

**Comment by Laurenbrady01** [comment]
Fixed the lines so they aren't so big 
![image](https://user-images.githubusercontent.com/55027585/110255564-0275f080-7f5a-11eb-9682-fc2c35445764.png)
