### ISSUE TITLE
Create/Find our existing UI to select a specific waypoint and guide the user towards it

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#58]
We don't have a good way to select a waypoint, it could be through a voice command, button press, or anything you think could work. Here is an example on a mobile device of this capability:
![image](https://user-images.githubusercontent.com/8094027/109873887-02ad7d80-7c34-11eb-9d0b-88233a9f66ed.png)

**Comment by Laurenbrady01** [comment]
Is this what we want?

![image](https://user-images.githubusercontent.com/55027585/110254338-65fd1f80-7f54-11eb-8542-22072187bba3.png)
