### ISSUE TITLE
Create indicators that change color based on telemetry state or good/bad status

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#60]
Make indicators like these that can change red, green, or yellow based on telemetry data such as oxygen or power level

![image](https://user-images.githubusercontent.com/8094027/109874140-56b86200-7c34-11eb-80db-a741aa817962.png)

**Comment by jamsteh** [comment]
Acceptable values https://drive.google.com/drive/u/1/folders/10pAQOflIniVcQdM-_zI-EOhRKob6iYl5
