### ISSUE TITLE
Implement Azure Custom Vision to identify a tool/rock/rover

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#71]
https://towardsdatascience.com/rapid-computer-vision-prototyping-with-azure-f051cc7462b7?gi=91334abfd0fb

**Comment by Laurenbrady01** [comment]
[https://www.customvision.ai/projects/041c81c8-cb46-4e45-99ad-b4f1e0cda5a4#/manage](url)

**Comment by Laurenbrady01** [comment]
![image](https://user-images.githubusercontent.com/55027585/113210463-e18f7b00-9239-11eb-9066-6f54093920c7.png)
