### ISSUE TITLE
Update Telemetry Stream with an event system

### ISSUE THREAD

**Issue by Henrynaut** [The12thAstronaut/SUITS-2021#8]
Jaime Vives: connect Unity value changed events to telemetry stream so UI can update OnChange()

**Comment by jamsteh** [comment]
PR: https://github.com/The12thAstronaut/SUITS-2021/pull/18

**Comment by jamsteh** [comment]
**How to test telemetry stream:**

1. Clone this repo to a directory: https://github.com/mc1998/new-suits-telemetry

2. Install npm (easiest way for Win10 powershell: via chocolatey)

3. run `npm install express` in the cloned directory

4. Navigate to directory and run `node app.js`

5. Hit the "Play" button in Unity
